"""iniciando migracion

Revision ID: 8b8a232b8f2d
Revises: 
Create Date: 2024-07-11 22:43:23.317207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b8a232b8f2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asociacion',
    sa.Column('id_asociacion', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('nombre_asociacion', sa.String(length=255), nullable=False),
    sa.Column('siglas', sa.String(length=20), nullable=False),
    sa.Column('fecha_constitucion', sa.Date(), nullable=False),
    sa.Column('fecha_digitacion', sa.DateTime(), nullable=True),
    sa.Column('objetivo', sa.Text(), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('representante_legal', sa.String(length=100), nullable=True),
    sa.Column('celular', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_asociacion')
    )
    op.create_table('asociado',
    sa.Column('nuip_asociado', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('tipo_nuip', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=70), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('estado_civil', sa.String(length=70), nullable=False),
    sa.Column('sexo', sa.String(length=20), nullable=False),
    sa.Column('poblacion_especial', sa.String(length=70), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('discapacidad_fisica', sa.String(length=20), nullable=True),
    sa.Column('celular', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('id_asociacion', sa.Integer(), nullable=False),
    sa.Column('cargo', sa.Integer(), nullable=True),
    sa.Column('fecha_digitacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_asociacion'], ['asociacion.id_asociacion'], ),
    sa.PrimaryKeyConstraint('nuip_asociado')
    )
    op.create_table('nucleo_familiar',
    sa.Column('nuip_miembro', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('tipo_nuip', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=70), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('estado_civil', sa.String(length=70), nullable=False),
    sa.Column('sexo', sa.String(length=20), nullable=False),
    sa.Column('poblacion_especial', sa.String(length=70), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('discapacidad_fisica', sa.String(length=20), nullable=True),
    sa.Column('celular', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('parentesco', sa.String(length=20), nullable=False),
    sa.Column('nuip_asociado', sa.Integer(), nullable=False),
    sa.Column('fecha_digitacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nuip_asociado'], ['asociado.nuip_asociado'], ),
    sa.PrimaryKeyConstraint('nuip_miembro')
    )
    op.create_table('predio',
    sa.Column('id_predio', sa.Integer(), nullable=False),
    sa.Column('nombre_predio', sa.String(length=100), nullable=False),
    sa.Column('ubicacion', sa.String(length=100), nullable=False),
    sa.Column('hectareas', sa.Integer(), nullable=False),
    sa.Column('nuip_asociado', sa.Integer(), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('fecha_digitacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nuip_asociado'], ['asociado.nuip_asociado'], ),
    sa.PrimaryKeyConstraint('id_predio'),
    sa.UniqueConstraint('nuip_asociado')
    )
    op.create_table('cultivo',
    sa.Column('id_cultivo', sa.Integer(), nullable=False),
    sa.Column('tipo_cultivo', sa.String(length=100), nullable=False),
    sa.Column('area_cultivada', sa.Integer(), nullable=False),
    sa.Column('fecha_siembra', sa.Date(), nullable=False),
    sa.Column('fecha_cosecha', sa.Date(), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('nuip_asociado', sa.Integer(), nullable=False),
    sa.Column('id_predio', sa.Integer(), nullable=False),
    sa.Column('fecha_digitacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_predio'], ['predio.id_predio'], ),
    sa.ForeignKeyConstraint(['nuip_asociado'], ['asociado.nuip_asociado'], ),
    sa.PrimaryKeyConstraint('id_cultivo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cultivo')
    op.drop_table('predio')
    op.drop_table('nucleo_familiar')
    op.drop_table('asociado')
    op.drop_table('asociacion')
    # ### end Alembic commands ###
